# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envelope.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='envelope.proto',
  package='',
  serialized_pb=_b('\n\x0e\x65nvelope.proto\"\xf3\x02\n\x08\x45nvelope\x12\x10\n\x08\x46ileName\x18\x01 \x01(\t\x12\x13\n\x0b\x43ontentType\x18\x02 \x01(\t\x12\x30\n\x0b\x43ompression\x18\x03 \x02(\x0e\x32\x1b.Envelope.CompressionMethod\x12\x11\n\tPublicKey\x18\x04 \x01(\t\x12\x11\n\tSignature\x18\x05 \x01(\t\x12\x12\n\nPartNumber\x18\x06 \x01(\r\x12\x12\n\nTotalParts\x18\x07 \x01(\r\x12\x10\n\x08PrevTxId\x18\x08 \x01(\t\x12\x0c\n\x04\x44\x61ta\x18\t \x02(\x0c\x12\x14\n\x0cPrevDataHash\x18\n \x01(\t\x12\x10\n\x08\x44\x61teTime\x18\x0b \x01(\r\x12\x0f\n\x07version\x18\x0c \x01(\r\"0\n\x11\x43ompressionMethod\x12\x08\n\x04None\x10\x00\x12\t\n\x05\x42zip2\x10\x01\x12\x06\n\x02Xz\x10\x02\"*\n\x0cUpdateMethod\x12\x0b\n\x07Replace\x10\x00\x12\r\n\tApplyDiff\x10\x01*\t\x08\x90N\x10\x80\x80\x80\x80\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_ENVELOPE_COMPRESSIONMETHOD = _descriptor.EnumDescriptor(
  name='CompressionMethod',
  full_name='Envelope.CompressionMethod',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='None', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Bzip2', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Xz', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=287,
  serialized_end=335,
)
_sym_db.RegisterEnumDescriptor(_ENVELOPE_COMPRESSIONMETHOD)

_ENVELOPE_UPDATEMETHOD = _descriptor.EnumDescriptor(
  name='UpdateMethod',
  full_name='Envelope.UpdateMethod',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Replace', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ApplyDiff', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=337,
  serialized_end=379,
)
_sym_db.RegisterEnumDescriptor(_ENVELOPE_UPDATEMETHOD)


_ENVELOPE = _descriptor.Descriptor(
  name='Envelope',
  full_name='Envelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='FileName', full_name='Envelope.FileName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ContentType', full_name='Envelope.ContentType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Compression', full_name='Envelope.Compression', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PublicKey', full_name='Envelope.PublicKey', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Signature', full_name='Envelope.Signature', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PartNumber', full_name='Envelope.PartNumber', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TotalParts', full_name='Envelope.TotalParts', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PrevTxId', full_name='Envelope.PrevTxId', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Data', full_name='Envelope.Data', index=8,
      number=9, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PrevDataHash', full_name='Envelope.PrevDataHash', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DateTime', full_name='Envelope.DateTime', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='Envelope.version', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ENVELOPE_COMPRESSIONMETHOD,
    _ENVELOPE_UPDATEMETHOD,
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(10000, 536870912), ],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=390,
)

_ENVELOPE.fields_by_name['Compression'].enum_type = _ENVELOPE_COMPRESSIONMETHOD
_ENVELOPE_COMPRESSIONMETHOD.containing_type = _ENVELOPE
_ENVELOPE_UPDATEMETHOD.containing_type = _ENVELOPE
DESCRIPTOR.message_types_by_name['Envelope'] = _ENVELOPE

Envelope = _reflection.GeneratedProtocolMessageType('Envelope', (_message.Message,), dict(
  DESCRIPTOR = _ENVELOPE,
  __module__ = 'envelope_pb2'
  # @@protoc_insertion_point(class_scope:Envelope)
  ))
_sym_db.RegisterMessage(Envelope)


# @@protoc_insertion_point(module_scope)
